"""Build a numeric-only 72px font from the project's MIT licensed LVGL font."""
from pathlib import Path
import re
from PIL import Image
root = Path(__file__).resolve().parent.parent
source = (root / 'Middlewares/lvgl/src/font/lv_font_montserrat_48.c').read_text(encoding='utf-8')
bitmap_block = source.split('glyph_bitmap[] = {', 1)[1].split('};', 1)[0]
bitmap_block = re.sub(r'/\*.*?\*/', '', bitmap_block, flags=re.S)
bitmap = bytes(int(n, 16) for n in re.findall(r'0x([0-9a-fA-F]+)', bitmap_block))
dsc_block = source.split('glyph_dsc[] = {', 1)[1].split('};', 1)[0]
descriptors = re.findall(r'\{([^{}]+)\}', dsc_block)
out = bytearray()
rows = ['{0,0,0,0,0,0}']
for codepoint in range(48, 59):
    values = [int(v) for v in re.findall(r'=\s*(-?\d+)', descriptors[codepoint - 32 + 1])]
    offset, advance, width, height, x, y = values
    pixels = []
    for i in range(width * height):
        byte = bitmap[offset + i // 2]
        pixels.append(((byte >> 4) if i % 2 == 0 else (byte & 15)) * 17)
    image = Image.new('L', (width, height))
    image.putdata(pixels)
    new_width, new_height = round(width * 1.5), round(height * 1.5)
    image = image.resize((new_width, new_height), Image.Resampling.LANCZOS)
    levels = [min(15, (v + 8) // 17) for v in image.get_flattened_data()]
    rows.append('{%d,%d,%d,%d,%d,%d}' % (len(out), round(advance * 1.5), new_width, new_height, round(x * 1.5), round(y * 1.5)))
    if len(levels) % 2: levels.append(0)
    out.extend((levels[i] << 4) | levels[i + 1] for i in range(0, len(levels), 2))
lines = [', '.join('0x%02x' % b for b in out[i:i + 20]) for i in range(0, len(out), 20)]
text = '''/* Derived from LVGL Montserrat 48; LVGL MIT license applies.
 * Generated by output/generate-clock-font.py. Digits and colon only. */
#include "lvgl.h"
static const uint8_t clock_bitmap[] = {
''' + ',\n'.join(lines) + '\n};\n'
text += 'static const lv_font_fmt_txt_glyph_dsc_t clock_glyphs[] = {\n' + ',\n'.join(rows) + '\n};\n'
text += '''static const lv_font_fmt_txt_cmap_t clock_cmap[] = {
    {.range_start=48, .range_length=11, .glyph_id_start=1, .type=LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY}
};
static const lv_font_fmt_txt_dsc_t clock_dsc = {
    .glyph_bitmap=clock_bitmap, .glyph_dsc=clock_glyphs, .cmaps=clock_cmap,
    .cmap_num=1, .bpp=4, .bitmap_format=0
};
const lv_font_t watch_font_clock_72 = {
    .get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,
    .line_height=78, .base_line=14, .dsc=&clock_dsc
};
'''
(root / 'App/watch_font_clock.c').write_text(text, encoding='utf-8')
print('Clock glyph bitmap:', len(out), 'bytes')
