"""Original code-drawn RGB565 backdrops. Static layers keep runtime drawing small."""
from pathlib import Path
from PIL import Image, ImageDraw
import math,random,struct
ROOT=Path(__file__).resolve().parents[1]
S=2
art=[]
def backdrop(name,painter):
 im=Image.new('RGB',(480*S,480*S));painter(im)
 im=im.resize((480,480),Image.Resampling.LANCZOS);im.save(ROOT/'output'/f'art-{name}.png')
 raw=b''.join(struct.pack('<H',((r>>3)<<11)|((g>>2)<<5)|(b>>3)) for r,g,b in im.getdata())
 art.append((name,raw,480,480,"RGB565",960))
def menu(im):
 px=im.load()
 for y in range(480*S):
  for x in range(480*S):
   a=math.exp(-(((x/S-190)/105)**2+((y/S-210)/100)**2))
   b=math.exp(-(((x/S-290)/110)**2+((y/S-295)/115)**2))
   px[x,y]=(int(7+7*a+11*b),int(13+18*a+8*b),int(24+21*a+18*b))
def sky(im):
 d=ImageDraw.Draw(im)
 for y in range(480*S):
  t=y/(480*S);d.line((0,y,480*S,y),fill=(int(5+7*t),int(18+78*t),int(43+92*t)))
 rng=random.Random(24)
 for i in range(42):
  x,y=rng.randrange(480*S),rng.randrange(310*S);d.ellipse((x,y,x+S,y+S),fill='#527c96')
 def poly(points,c):d.polygon([(int(x*S),int(y*S)) for x,y in points],fill=c)
 for offset,c in [(0,'#24566d'),(30,'#193e56')]:
  points=[(0,430),(0,370+offset)]+[(x,352+offset-24*math.sin(x/60)) for x in range(0,481,12)]+[(480,480),(0,480)];poly(points,c)
 for cx,cy in [(95,178),(405,252)]:
  for dx,dy,r in [(-28,0,18),(0,-12,26),(27,0,19)]:
   x,y=(cx+dx)*S,(cy+dy)*S;d.ellipse((x-r*S,y-r*S,x+r*S,y+r*S),fill='#2d5773')
  d.rounded_rectangle((int((cx-48)*S),int(cy*S),int((cx+48)*S),int((cy+19)*S)),12*S,fill='#2d5773')
 d.rectangle((0,408*S,480*S,480*S),fill='#efcb8b');d.line((0,408*S,480*S,408*S),fill='#fff2cc',width=6*S)
 for x in range(40,481,62):d.ellipse((x*S,436*S,(x+15)*S,441*S),fill='#d5ae71')
def radar(im):
 d=ImageDraw.Draw(im);d.rectangle((0,0,480*S,480*S),fill='#04131e')
 def xy(p):return tuple(int(v*S) for v in p)
 rng=random.Random(19)
 # Fictional chart texture; no claims of actual geographic location.
 for side in [-1,1]:
  points=[]
  for y in range(120,367,10):
   x=240+side*(150+18*math.sin(y/28)+rng.uniform(-9,9));points.append((x,y))
  points.extend([(0 if side<0 else 480,367),(0 if side<0 else 480,120)])
  d.polygon([xy(p) for p in points],fill='#14333d');d.line([xy(p) for p in points[:-2]],fill='#34575b',width=S)
 for r in [52,102,152]:d.ellipse(xy((240-r,240-r,240+r,240+r)),outline='#438b92',width=S)
 d.ellipse(xy((29,29,451,451)),outline='#2b778f',width=S)
 for deg in range(0,360,10):
  a=math.radians(deg);r=203 if deg%30 else 197
  d.line([xy((240+r*math.sin(a),240-r*math.cos(a))),xy((240+211*math.sin(a),240-211*math.cos(a)))],fill='#78c4d6',width=S)
 d.line([xy((88,240)),xy((392,240))],fill='#245968',width=S)
 d.line([xy((240,88)),xy((240,392))],fill='#245968',width=S)
 # Pre-baked alpha sweep; static by request.
 layer=Image.new('RGBA',im.size);ld=ImageDraw.Draw(layer)
 for a in range(-90,-54):ld.pieslice(xy((88,88,392,392)),a,a+1,fill=(77,230,200, int(4+(a+90)*2)))
 im.paste(layer,(0,0),layer);d=ImageDraw.Draw(im)
 for i in range(12):
  x=154+i*6.8;y=297-0.37*i*i;d.ellipse(xy((x-2,y-2,x+2,y+2)),fill='#7bc8b9')
 for t in range(0,101,8):
  x=240+.96*t;y=240-.9*t;d.ellipse(xy((x-1,y-1,x+1,y+1)),fill='#ffd18b')
 d.ellipse(xy((328,141,342,155)),outline='#ffd18b',width=2*S)
 d.polygon([xy(p) for p in [(251,228),(246,246),(239,241),(229,245)]],fill='#99f7de')
 for x,y in [(156,152),(358,282)]:
  d.ellipse(xy((x-3,y-3,x+3,y+3)),fill='#83ebd5')
backdrop('menu_wallpaper',menu);backdrop('flappy_sky',sky);backdrop('ida_radar',radar)
bird=Image.new('RGBA',(56*S,56*S));bd=ImageDraw.Draw(bird)
bd.ellipse((6*S,15*S,44*S,43*S),fill='#fff0c7');bd.ellipse((3*S,29*S,27*S,43*S),fill='#e6a05d')
bd.ellipse((30*S,16*S,44*S,30*S),fill='#38435b');bd.ellipse((34*S,19*S,38*S,23*S),fill='#fff7e7')
bd.polygon([(43*S,29*S),(54*S,33*S),(43*S,37*S)],fill='#e790a4')
bird=bird.resize((56,56),Image.Resampling.LANCZOS);bird.save(ROOT/'output/art-bird_sprite.png')
raw=bytes(c for r,g,b,a in bird.getdata() for c in (b,g,r,a));art.append(('bird_sprite',raw,56,56,'ARGB8888',224))
lines=['/* Generated by output/generate-arcade-art.py. */','#include "views/watch_art.h"']
for name,raw,w,h,cf,stride in art:
 lines.append(f'static const uint8_t {name}_pixels[] __attribute__((aligned(4))) = {{')
 for i in range(0,len(raw),32):lines.append(','.join(f'0x{x:02x}' for x in raw[i:i+32])+',')
 lines.extend(['};',f'const lv_image_dsc_t {name} = {{', f'.header={{.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_{cf},.w={w},.h={h},.stride={stride}}},',f'.data_size=sizeof {name}_pixels,.data={name}_pixels','};'])
(ROOT/'App/views/watch_art.c').write_text('\n'.join(lines)+'\n')
(ROOT/'App/views/watch_art.h').write_text('#ifndef WATCH_ART_H\n#define WATCH_ART_H\n#include "lvgl.h"\n'+''.join(f'extern const lv_image_dsc_t {n};\n' for n,*_ in art)+'#endif\n')
