"""Generate our small, original two-tone watch icons; no runtime SVG parsing."""
from pathlib import Path
from PIL import Image, ImageDraw
import math

ROOT = Path(__file__).resolve().parents[1]
S = 4
names = ['clock', 'alarm', 'calculator', 'notes', 'faces', 'water', 'calendar', 'settings']
backgrounds = ['#9cafff', '#ff9b9e', '#96e1c2', '#e5c191', '#d7aff7', '#82d9f4', '#ffc5a2', '#adc4d6']
output = ['/* Original icons, generated by output/generate-menu-icons.py. */', '#ifndef WATCH_ICONS_H', '#define WATCH_ICONS_H', '#include "lvgl.h"']
for name, bg in zip(names, backgrounds):
    im = Image.new('RGBA', (64*S, 64*S))
    d = ImageDraw.Draw(im)
    def box(b): return tuple(round(v*S) for v in b)
    def ellipse(b, fill, outline=None, width=2): d.ellipse(box(b), fill, outline, width*S)
    def rect(b, fill, r=4): d.rounded_rectangle(box(b), r*S, fill)
    def line(p, fill='#38435b', w=3):
        d.line([(round(x*S), round(y*S)) for x,y in p], fill, w*S, joint='curve')
        for x,y in (p[0],p[-1]): ellipse((x-w/2,y-w/2,x+w/2,y+w/2),fill)
    ink = '#38435b'
    if name == 'clock':
        ellipse((10,10,54,54), '#fff7ef')
        ellipse((14,14,50,50), None, ink,2)
        line([(32,21),(32,32),(42,36)],ink,3)
        ellipse((29,29,35,35), '#f78198')
    elif name == 'alarm':
        ellipse((25,46,39,59),'#fff2db')
        rect((28,5,36,17),ink,4)
        ellipse((17,13,47,44),'#fff2db')
        d.polygon([box(p) for p in [(18,28),(46,28),(47,41),(54,48),(10,48),(17,41)]],fill='#fff2db')
        rect((9,44,55,51),'#fff2db',4)
        line([(24,23),(23,31)],'#d992ab',3)
        line([(8,19),(5,26)],ink,3); line([(56,19),(59,26)],ink,3)
    elif name == 'calculator':
        rect((14,5,50,59),ink,8); rect((19,11,45,25),'#e8fff6',3)
        for y in (31,41,51):
            for x in (23,33,43): ellipse((x-3,y-3,x+3,y+3),'#ffbe9d' if x==43 else '#f5fff9')
    elif name == 'notes':
        rect((13,8,51,56),'#fff8e8',6)
        for y in (21,31,41): line([(21,y),(42,y)],'#a092b7',3)
        line([(16,7),(16,55)],'#b597cb',4)
        line([(42,49),(56,34)],'#e790a4',6)
    elif name == 'faces':
        rect((23,1,41,63),'#73538e',6); rect((10,12,54,52),'#fff4fb',12)
        rect((15,17,49,47),ink,9)
        line([(24,34),(30,28),(36,36),(42,25)],'#edaaf0',3)
        ellipse((29,40,35,44),'#8edfd4')
    elif name == 'water':
        points=[(32,5),(48,26),(51,38),(47,49),(38,56),(26,56),(17,49),(13,38),(16,26)]
        d.polygon([(x*S,y*S) for x,y in points], fill='#f1fcff')
        ellipse((13,24,51,57),'#f1fcff')
        line([(22,35),(22,42),(27,47)],'#5cafd5',4)
    elif name == 'calendar':
        rect((9,11,55,56),'#fff7ef',7); rect((9,11,55,25),'#e58396',5)
        line([(21,7),(21,17)],ink,4); line([(43,7),(43,17)],ink,4)
        for x,y in [(20,34),(32,34),(44,34),(20,45),(32,45),(44,45)]:
            ellipse((x-3,y-3,x+3,y+3), '#e58396' if (x,y)==(32,34) else '#94a3ba')
    else:
        for i in range(8):
            a=i*math.pi/4
            x,y=32+21*math.cos(a),32+21*math.sin(a)
            ellipse((x-7,y-7,x+7,y+7), '#f5f8ff')
        ellipse((10,10,54,54),'#f5f8ff'); ellipse((21,21,43,43),ink); ellipse((27,27,37,37),bg)
    im = im.resize((64,64), Image.Resampling.LANCZOS)
    im.save(ROOT/'output'/f'icon-{name}.png')
    # LVGL ARGB8888 memory is BGRA on this little-endian target.
    data=bytearray()
    for r,g,b,a in im.getdata(): data.extend((b,g,r,a))
    output.append(f'static const uint8_t icon_{name}_pixels[] = {{')
    for offset in range(0,len(data),32): output.append(','.join(f'0x{v:02x}' for v in data[offset:offset+32])+',')
    output.extend(['};', f'static const lv_image_dsc_t icon_{name} = {{', '.header = {.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_ARGB8888, .w = 64, .h = 64, .stride = 256},', f'.data_size = sizeof icon_{name}_pixels, .data = icon_{name}_pixels', '};'])
output.append('#endif')
(ROOT/'App'/'watch_icons.h').write_text('\n'.join(output)+'\n')
